# Generated by Django 3.2.8 on 2021-10-31 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allauth_emailaddres',
        ),
    ]
